# Generated by Django 3.1.3 on 2022-10-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_auto', models.CharField(max_length=20)),
                ('valor', models.FloatField()),
                ('costos', models.FloatField()),
                ('arreglos', models.CharField(max_length=100)),
            ],
        ),
    ]
